runtime: python39

entrypoint: gunicorn -b :$PORT salesite.wsgi

env_variables:
  DJANGO_SETTINGS_MODULE: "salesite.settings"

handlers:
- url: /static
  static_dir: static/

- url: /.*
  script: auto
