# Generated by Django 4.1.5 on 2023-03-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='brand_logos')),
                ('sale', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='subscriber',
            name='brands',
            field=models.ManyToManyField(to='saleapp.brand'),
        ),
    ]
