# Generated by Django 4.1.7 on 2023-03-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleapp', '0005_alter_brand_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.FileField(upload_to='salesite\\saleapp\\static\x08rand_logos'),
        ),
    ]
