# Generated by Django 4.1.7 on 2023-04-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleapp', '0008_subscriber_confirmation_sent_subscriber_confirmed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='logo',
        ),
        migrations.AddField(
            model_name='brand',
            name='logo_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
