# Generated by Django 4.1.7 on 2023-04-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleapp', '0009_remove_brand_logo_brand_logo_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='logo_data',
        ),
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
