# Generated by Django 4.1.7 on 2023-04-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleapp', '0010_remove_brand_logo_data_brand_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='brand_logos/'),
        ),
    ]
